# Generated by Django 3.1.1 on 2020-09-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(blank=True, max_length=250)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
