# Generated by Django 3.1.1 on 2020-09-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Signup',
        ),
    ]
