# Generated by Django 3.1.1 on 2020-09-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200917_1121'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='signup',
            table='web_Signup',
        ),
    ]
