# Generated by Django 3.1.1 on 2020-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200917_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('copname', models.CharField(max_length=120)),
                ('jobtitle', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('population', models.CharField(choices=[('pone', 'pone'), ('ptwo', 'ptwo'), ('pthree', 'pthree'), ('pfour', 'pfour'), ('pfive', 'pfive'), ('psix', 'psix'), ('pseven', 'pseven')], max_length=10)),
                ('job', models.CharField(choices=[('jobone', 'job'), ('jobtwo', 'job'), ('jobthree', 'job')], max_length=128)),
                ('employment', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3')], max_length=128)),
                ('contract', models.CharField(choices=[('contract1', 'çontract1'), ('contract2', 'çontract2'), ('contract3', 'çontract3'), ('contract4', 'çontract4'), ('contract5', 'çontract5'), ('contract6', 'çontract6'), ('contract7', 'çontract7')], max_length=128)),
                ('amount1', models.IntegerField()),
                ('amount2', models.IntegerField()),
                ('per', models.CharField(choices=[('perone', 'perone'), ('pertwo', 'pertwo'), ('perthree', 'perthree'), ('perfour', 'perfour'), ('perfive', 'perfive')], max_length=100)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
