# Generated by Django 3.1.1 on 2020-09-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_employ_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ_form',
            old_name='job_title',
            new_name='jobtitle',
        ),
    ]
