# Generated by Django 3.1.1 on 2020-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200920_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ_Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_population', models.CharField(choices=[('pone', 'pone'), ('ptwo', 'ptwo'), ('pthree', 'pthree'), ('pfour', 'pfour'), ('pfive', 'pfive'), ('psix', 'psix'), ('pseven', 'pseven')], max_length=10)),
                ('job', models.CharField(choices=[('jobone', 'job'), ('jobtwo', 'job'), ('jobthree', 'job')], max_length=128)),
                ('employment', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3')], max_length=128)),
                ('contract', models.CharField(choices=[('contract1', 'çontract1'), ('contract2', 'çontract2'), ('contract3', 'çontract3'), ('contract4', 'çontract4'), ('contract5', 'çontract5'), ('contract6', 'çontract6'), ('contract7', 'çontract7')], max_length=128)),
            ],
        ),
    ]
