# Generated by Django 3.1.1 on 2020-09-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_employ_form2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_form2',
            name='contract',
            field=models.CharField(choices=[('contract1', 'çontract'), ('contract2', 'çontract'), ('contract3', 'çontract'), ('contract4', 'çontract'), ('contract5', 'çontract'), ('contract6', 'çontract'), ('contract7', 'çontract')], max_length=128),
        ),
        migrations.AlterField(
            model_name='employer_form',
            name='contract',
            field=models.CharField(choices=[('contract1', 'çontract'), ('contract2', 'çontract'), ('contract3', 'çontract'), ('contract4', 'çontract'), ('contract5', 'çontract'), ('contract6', 'çontract'), ('contract7', 'çontract')], max_length=128),
        ),
    ]
