# Generated by Django 3.1.1 on 2020-09-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200921_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ_form2',
            name='contract',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employ_form2',
            name='employment',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employ_form2',
            name='job',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employ_form2',
            name='my_population',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employer_form',
            name='contract',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employer_form',
            name='employment',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employer_form',
            name='job',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='employer_form',
            name='per',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employer_form',
            name='population',
            field=models.CharField(max_length=10),
        ),
    ]
