# Generated by Django 3.1.1 on 2020-09-21 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
