# Generated by Django 3.1.1 on 2020-09-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_delete_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='mail',
            new_name='email',
        ),
    ]
