# Generated by Django 3.1.1 on 2020-09-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_employ_form3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employ_Form3',
        ),
    ]
