# Generated by Django 3.1.1 on 2020-09-23 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20200922_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
