# Generated by Django 3.1.1 on 2020-09-23 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_delete_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
