# Generated by Django 3.1.1 on 2020-09-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_delete_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
