# Generated by Django 3.1.1 on 2020-09-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating_figures', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=500)),
                ('work1', models.CharField(max_length=500)),
                ('work2', models.CharField(max_length=500)),
                ('work3', models.CharField(max_length=500)),
                ('work4', models.CharField(max_length=500)),
                ('loc1', models.CharField(max_length=500)),
                ('loc2', models.CharField(max_length=500)),
                ('loc3', models.CharField(max_length=500)),
                ('loc4', models.CharField(max_length=500)),
                ('role1', models.CharField(max_length=500)),
                ('role2', models.CharField(max_length=500)),
                ('role3', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
