# Generated by Django 3.1.1 on 2020-09-26 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='role1',
            new_name='job1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='role2',
            new_name='job2',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='role3',
            new_name='job3',
        ),
    ]
