# Generated by Django 3.1.1 on 2020-09-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_auto_20200929_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('requirements', models.TextField()),
                ('details', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
