# Generated by Django 3.1.1 on 2020-09-30 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
