# Generated by Django 3.1.1 on 2020-10-01 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
